apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: shopping-app:latest
        ports:
        - containerPort: 8080